### ISSUE TITLE
Error E04: Could not resolve type: 'I2C.LiteX_I2C_Zephyr'.

### ISSUE THREAD

**Issue by bloom5** [antmicro/litex-vexriscv-tensorflow-lite-demo#25]
Renode, version 1.11.0.28399 (ad7ab75a-202010221522)
(monitor) i $CWD/litex-vexriscv-tflite.resc
Errors during compilation or loading:
There were compilation errors:
e:\litex-vexriscv-tensorflow-lite-demo\renode\LiteX_I2C_Zephyr.cs(93,26) : error CS1002: 
 ;
There was an error executing command 'machine LoadPlatformDescription E:\litex-vexriscv-tens
orflow-lite-demo\renode\litex-vexriscv-tflite.repl'
Error E04: Could not resolve type: 'I2C.LiteX_I2C_Zephyr'.
At E:\litex-vexriscv-tensorflow-lite-demo\renode\litex-vexriscv-tflite.repl:23:6:
i2c: I2C.LiteX_I2C_Zephyr @ {
     ^^^^^^^^^^^^^^^^^^^^^
![image](https://user-images.githubusercontent.com/1779920/99505888-5ca77180-29bc-11eb-92a2-626800869c73.png)

**Comment by PiotrZierhoffer** [comment]
Are you running on Windows? This looks like your .net runs a compilation against different version of C#. I pushed a fix on master that should solve it for you.

**Comment by bloom5** [comment]
Yes, I am running Windows 10. I still have the error reported in the monitor. 
Since you mentioned .net, here is the info of dotnet on my PC:
dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by PiotrZierhoffer** [comment]
Can you please double check if the error message you get is the same?

**Comment by bloom5** [comment]
It not exactly the same, more lines in LiteX_I2C_Zephyr.cs are reported Error
![image](https://user-images.githubusercontent.com/1779920/100327622-7f620780-3006-11eb-8f3f-5926de5ba133.png)

**Comment by PiotrZierhoffer** [comment]
I just pushed yet another version. I compiled it on Windows successfully, and was able to reproduce your errors, so I think it should work fine for you as well.

**Comment by bloom5** [comment]
Yes, it works.
